# Generated by Django 5.1.2 on 2024-11-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskCategory', '0002_remove_category_category'),
        ('taskModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='category',
            field=models.ManyToManyField(to='taskCategory.category'),
        ),
    ]
